symfony/marketing

views/en/community/irc.html.twig
mIRC requires registration after 30 days, HexChat also works on Windows :+1:
=> add HexChat for Windows IRC clients

translations/marketing.fr.xliff, views/fr/community/mailing_lists.html.twig, views/fr/get_started/components.html.twig, views/fr/what_is_symfony/at_a_glance.html.twig
I've updated the few french pages to match the latest commits.
=> [fix] french version

translations/marketing.sl.xliff, views/sl/what_is_symfony.html.twig, views/sl/what_is_symfony/distributions.html.twig, views/sl/what_is_symfony/download.html.twig
Fixes and updates of the Slovenian translation according to the new file structure and English version updates.
=> [fix] [sl] Slovenian translation fix

views/en/community/mailing_lists.html.twig, views/es/community/mailing_lists.html.twig
This replaces #266 and fixes #271.
=> Updated the contents of the Mailing List page

translations/marketing.es.xliff
This PR finishes the work done in #154.
=> Finished Spanish translation of the menu items

views/id/about.html.twig
Hi,
Thanks for providing this opportunity to involve in Sf2,
You can view my profile at ardianys.com
Thanks.
=> [id] Indonesian translation of the "About" page

views/de/community.html.twig, views/de/community/get_in_touch.html.twig, views/de/community/mailing_lists.html.twig, views/de/what_is_symfony.html.twig, views/de/what_is_symfony/at_a_glance.html.twig, views/de/what_is_symfony/components.html.twig, views/de/what_is_symfony/download.html.twig, views/de/what_is_symfony/elevator_pitches.html.twig, views/de/what_is_symfony/elevator_pitches/explained_to_a_developer.html.twig, views/de/what_is_symfony/elevator_pitches/explained_to_a_project_manager.html.twig, views/de/what_is_symfony/elevator_pitches/explained_to_a_project_owner.html.twig, views/de/what_is_symfony/elevator_pitches/explained_to_a_system_administrator.html.twig, views/de/what_is_symfony/elevator_pitches/explained_to_my_boss.html.twig, views/de/what_is_symfony/in_five_minutes.html.twig, views/de/what_is_symfony/in_five_minutes/six_good_reasons.html.twig, views/de/what_is_symfony/in_five_minutes/six_technical_reasons.html.twig, views/de/what_is_symfony/in_five_minutes/ten_criteria.html.twig, views/de/what_is_symfony/in_five_minutes/when_use_a_framework.html.twig, views/de/what_is_symfony/in_five_minutes/why_use_a_framework.html.twig
This finishes #105.
@OskarStark I'm going to merge this PR as it is because we've already waited two years to merge it. Once merged, you and other German-speaking volunteers can contribute fixes and tweaks on a page-by-page basis. Thanks!
=> Updates to the German translation

views/id/about.html.twig
ass recommended by @samsonasik
in: https://github.com/symfony/symfony-marketing/pull/55/files#r13033909
refs #55
=> minor text change

views/en/community/mailing_lists.html.twig, views/en/community/support.html.twig, views/es/community/mailing_lists.html.twig, views/es/community/support.html.twig, views/sl/community/mailing_lists.html.twig, views/sl/community/support.html.twig
This patch fixes some Stack Overflow links and some naming of the site.
=> Fix Stack Overflow names and links

views/en/what_is_symfony/download.html.twig, views/es/what_is_symfony/download.html.twig
Dear community translators, don't update your translations yet because this is still a proposal. Thanks!
=> Updated the contents of the "Download" page

views/ca/about.html.twig, views/cs/about.html.twig, views/de/about.html.twig, views/en/about.html.twig, views/es/about.html.twig, views/fr/about.html.twig, views/hu/about.html.twig, views/id/about.html.twig, views/it/about.html.twig, views/nl/about.html.twig, views/pl/about.html.twig, views/pt/about.html.twig, views/pt_BR/about.html.twig, views/ro/about.html.twig, views/ru/about.html.twig, views/sk/about.html.twig, views/sl/about.html.twig, views/sv/about.html.twig, views/zh/about.html.twig, views/zh_CN/about.html.twig
The "About" page will be soon translatable again, so we need to update the current contents for the new page structure.
=> [fix] Updated the "About" page translations

projects/piwik.yml
=> Added missing components used by Piwik

projects/en/backbee.html.twig, projects/en/behat.html.twig, projects/en/bolt.html.twig, projects/en/carew.html.twig, projects/en/elcodi.html.twig, projects/en/forkcms.html.twig, projects/en/freepost.html.twig, projects/en/initcms.html.twig, projects/en/kunstmaanbundles.html.twig, projects/en/ladybug.html.twig, projects/en/magento.html.twig, projects/en/mothership.html.twig, projects/en/orocrm.html.twig, projects/en/oroplatform.html.twig, projects/en/pagekit.html.twig, projects/en/phinx.html.twig, projects/en/phpredexpert.html.twig, projects/en/phpspec.html.twig, projects/en/ppi.html.twig, projects/en/redkitecms.html.twig, projects/en/roadiz.html.twig, projects/en/silex.html.twig, projects/en/sismo.html.twig, projects/en/sonataecommerce.html.twig, projects/en/sonataproject.html.twig, projects/en/sulu.html.twig, projects/en/sylius.html.twig, projects/en/symfonycmf.html.twig, projects/en/vespolina.html.twig
Most projects had a brief description based on a single `<p>` element with no other HTML contents. This pull request makes all projects follow that syntax.
=> Fixed the description of all projects

projects/en/wellcommerce.html.twig
This patch fixes some typos according to current project descriptions.
=> Some typos in WellCommerce

views/cs/what-is-symfony/elevator-pitches.html.twig, views/de/what-is-symfony/elevator-pitches.html.twig, views/en/what-is-symfony/elevator-pitches.html.twig, views/fr/what-is-symfony/elevator-pitches.html.twig, views/fr/what-is-symfony/elevator-pitches/explained-to-a-project-owner.html.twig, views/nl/what-is-symfony/elevator-pitches.html.twig, views/pl/what-is-symfony/elevator-pitches.html.twig, views/pt/what-is-symfony/elevator-pitches.html.twig, views/pt_BR/what-is-symfony/elevator-pitches.html.twig, views/sl/what-is-symfony/elevator-pitches.html.twig, views/zh/what-is-symfony/elevator-pitches.html.twig, views/zh_CN/what-is-symfony/elevator-pitches.html.twig
Besides the template names, I fixed an issue reported by `twig:lint` command.
=> Fixed wrong template names

views/en/what-is-symfony.html.twig
" ... on which the best PHP applications are built on ..." is redundant.
Also, added Oxford comma in a couple places.
=> Small grammar and punctuation fix

views/ca/what-is-symfony.html.twig, views/cs/what-is-symfony.html.twig, views/de/what-is-symfony.html.twig, views/en/what-is-symfony.html.twig, views/es/what-is-symfony.html.twig, views/fr/what-is-symfony.html.twig, views/hu/what-is-symfony.html.twig, views/it/what-is-symfony.html.twig, views/nl/what-is-symfony.html.twig, views/pl/what-is-symfony.html.twig, views/pt/what-is-symfony.html.twig, views/pt_BR/what-is-symfony.html.twig, views/ro/what-is-symfony.html.twig, views/ru/what-is-symfony.html.twig, views/sk/what-is-symfony.html.twig, views/sl/what-is-symfony.html.twig, views/sv/what-is-symfony.html.twig, views/sv/what-is-symfony/elevator-pitches.html.twig, views/zh/what-is-symfony.html.twig, views/zh_CN/what-is-symfony.html.twig
=> Fixed the links to two Elevator Pitches pages

projects/_projects.yml, projects/freepost.yml
See issue #354 for more information.
=> Adjust freepo.st project due to feedback and research.

projects/de/aimeos.html.twig, projects/de/pagekit.html.twig, projects/en/aimeos.html.twig, projects/en/morfeu.html.twig, projects/en/phpredexpert.html.twig, projects/sl/aimeos.html.twig, projects/sl/morfeu.html.twig
This patch updates code style used in Twig templates for projects as noted in https://github.com/symfony/symfony-marketing/pull/361#discussion-diff-68047168
=> Fix CS in projects

projects/_components.yml
Question: should [Polyfill components](https://github.com/symfony/polyfill) be added to this list too? All of them individually? Thanks!
=> Added some missing Symfony Components

projects/en/sonataproject.html.twig
The admin part of the Sonata project is far more active than the
e-commerce part, I think this description is more accurate.
=> Remove focus on e-commerce

projects/_components.yml
=> Added PHPUnit Bridge "component" to the list of components

projects/sl/apiplatform.html.twig, projects/sl/prestashop.html.twig, projects/sl/silverstripe.html.twig, projects/sl/sonataproject.html.twig, projects/sl/victoire.html.twig, projects/sl/wallabag.html.twig, translations/component.sl.xliff
This patch updates and syncs sl_SI translations with English version.
=> [fix] [sl] Update translations

views/nl/about.html.twig, views/nl/community.html.twig, views/nl/community/get-in-touch.html.twig, views/nl/what-is-symfony.html.twig, views/nl/what-is-symfony/components.html.twig, views/nl/what-is-symfony/distributions.html.twig, views/nl/what-is-symfony/download.html.twig, views/nl/what-is-symfony/projects.html.twig
I went over the nl translations and corrected some errors I found. 
Sentence constructions and grammar.
=> nl translations corrections

components.yml
Added:
* Lock
* WebLink
* Polyfill PHP 7.2
=> Added the missing Symfony components

projects/eccube.yml
`EC-CUBE` is correct, not 'eccube'
=> Fixed eccube name

projects.yml, projects/psysh.yml
1.3M+ installs a month, and at least five other projects on this list are (or include) shells based on PsySH 😃
=> Add PsySH to projects list.

projects/joomla.yml
This adds stable Joomla! Framework components with direct dependencies to Symfony components, an additional joomla.org website using Symfony components, and adds comments noting where the dependencies come from
=> Add Joomla! repositories

projects.yml
Sorry forget to change this one in the previous PR
=> Rename csbill to solidinvoice in projects.yml

components.yml
This fixes https://github.com/symfony/symfony-docs/issues/8922
=> Added the link to the Lock component docs

components.yml
This description was the only one not following the style of the other descriptions.
=> Reworded the description of the PhpUnitBridge component

projects/ezplatform.yml
Changes "The eZ Platform" to simply "eZ Platform", and restructures the sentences for a more natural flow.
=> Grammar and readability improvements

projects/ppi.yml, projects/sonataecommerce.yml
=> Fixed some wrongly escaped chars

projects/yii.yml
They were using a Symfony component without explicitly requiring it, so we fixed that in https://github.com/yiisoft/yii2-shell/pull/16/files
=> Updated the dependencies of Yii2

components.yml
The introduction phrase in https://github.com/symfony/symfony-docs/pull/9437 is cut ... so I don't know how to describe this component. @sroze is the "message bus" reference correct in this case? Can you think of a better phrase to describe this component precisely and concisely? Thanks!
=> Added the Messenger component

components.yml
The docs have just been merged, so they haven't been generated on the symfony.com server yet. Let's wait a few minutes/hours before merging this. Thanks!
=> Added the links to the Polyfill docs

projects/orocommerce.yml, projects/orocrm.yml, projects/oroplatform.yml
=> Updated the dependencies of Oro projects

projects/zikula.yml
As requested by @Guite from the Zikula project.
=> Updated the URL of the Zikula project

projects.yml
Moved testing frameworks to Code Quality section.
=> Moved testing frameworks to Code Quality section.

projects/automate.yml
Hello,
We leave Github Page for this project.
Same site, same project, only domain change
Thank you
=> Update automate domain

components.yml
The Mailer docs are a placeholder for now, but they will be published soon.
=> Linked the docs for Mime and Mailer

components.yml
The docs are not available yet ... but they will be merged soon (https://github.com/symfony/symfony-docs/pull/11419).
=> Added Inflector as component

components.yml
The docs will be soon merged: https://github.com/symfony/symfony-docs/pull/11430
=> Linked the new Contracts component docs

projects/phpmyadmin.yml
https://github.com/phpmyadmin/sql-parser/blob/master/composer.json
=> Update phpmyadmin.yml to add sql-parser project

components.yml
Don't merge until its doc PR is merged (https://github.com/symfony/symfony-docs/pull/12820). Thanks!
=> Added the Polyfill UUID component

components.yml
DON'T MERGE this until the related docs are merged (https://github.com/symfony/symfony-docs/pull/13338). Thanks.
=> Added the UID component

components.yml
Related to https://github.com/symfony/symfony-docs/issues/13638
=> Deprecate the Inflector component

components.yml
The doc of these components has been moved into other Symfony Doc pages.
=> Updated the main doc page of some components

components.yml
In addition to adding missing components, it rewords the description of PHP polyfill components to better explain their purpose.
=> Add some missing polyfill components

projects/crunz.yml
Crunz changed repository: https://github.com/lavary/crunz/issues/411
=> Change Crunz repository

projects/shopware.yml
=> Fix a wrong end point
